import { type Property } from './supabase';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Apartment',
    description: 'Beautiful 2-bedroom apartment in the heart of downtown with stunning city views.',
    property_type: 'apartment',
    status: 'available',
    price: 2500,
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1200,
    address: '123 Main Street',
    city: 'New York',
    state: 'NY',
    zip_code: '10001',
    image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Luxury Family Home',
    description: 'Spacious 4-bedroom family home with large backyard and modern amenities.',
    property_type: 'house',
    status: 'available',
    price: 4500,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 2500,
    address: '456 Oak Avenue',
    city: 'Los Angeles',
    state: 'CA',
    zip_code: '90001',
    image_url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Cozy Studio Condo',
    description: 'Perfect starter home in a great neighborhood with easy access to public transport.',
    property_type: 'condo',
    status: 'available',
    price: 1800,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 600,
    address: '789 Pine Street',
    city: 'Chicago',
    state: 'IL',
    zip_code: '60601',
    image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Elegant Townhouse',
    description: 'Stylish 3-bedroom townhouse with modern finishes and private garage.',
    property_type: 'townhouse',
    status: 'available',
    price: 3200,
    bedrooms: 3,
    bathrooms: 2.5,
    area_sqft: 1800,
    address: '321 Elm Drive',
    city: 'Miami',
    state: 'FL',
    zip_code: '33101',
    image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Beachfront Villa',
    description: 'Luxurious 5-bedroom villa with ocean views and private pool.',
    property_type: 'villa',
    status: 'available',
    price: 8500,
    bedrooms: 5,
    bathrooms: 4,
    area_sqft: 4000,
    address: '555 Ocean Boulevard',
    city: 'San Diego',
    state: 'CA',
    zip_code: '92101',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Urban Loft Apartment',
    description: 'Modern loft-style apartment with high ceilings and industrial design.',
    property_type: 'apartment',
    status: 'available',
    price: 2200,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 900,
    address: '888 Market Street',
    city: 'San Francisco',
    state: 'CA',
    zip_code: '94102',
    image_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
